# Generated by Django 4.2.11 on 2024-03-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=25)),
                ('landmark', models.CharField(max_length=25)),
                ('dmail', models.CharField(max_length=25)),
                ('period', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=25)),
                ('dpassword', models.CharField(max_length=25)),
                ('demail', models.CharField(max_length=25)),
                ('darea', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='drivstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivername', models.CharField(default='default', max_length=25)),
                ('area', models.CharField(default='default', max_length=25)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complited', 'Complited'), ('declained', 'Declained')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='regcomp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarea', models.CharField(max_length=25)),
                ('remail', models.CharField(max_length=25)),
                ('rcomp', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declained', 'Declained')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
    ]
