# Generated by Django 5.1.1 on 2024-10-25 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='garbageapp.regcomp'),
        ),
    ]
