# Generated by Django 5.1.1 on 2024-10-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0003_bin_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='regcomp',
            name='raddress',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
