# Generated by Django 5.1.1 on 2024-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageapp', '0004_regcomp_raddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='regcomp',
            name='username',
            field=models.CharField(default='username', max_length=25),
        ),
    ]
